# Tutorial 1: Explore Numpy Library to Analyze Data

**Task: Perform basic operations like array creation, indexing, slicing, and mathematical operations.**

>Description: Use Numpy library for numerical data analysis.

>Dataset: Randomly generated numerical data.

**1.Import numpy library.**

In [1]:
import numpy as np

**2.Create 1D array with 5 elements.**

In [ ]:
#using np.array function to create 1D array
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

**Create 1D array with 5 elements random value. (by default values between 0 to 1)**

In [ ]:
random_array = np.random.rand(5)
random_array

array([0.02000573, 0.67663017, 0.28965696, 0.87503407, 0.34945182])

**4.Generate random value from range 5 to 15 with 1D array size 10.**

In [ ]:
random_array = np.random.randint(5, 15, size=10)
random_array

array([ 6,  9,  9,  9,  6, 14,  5,  8, 10, 13])

**5.Create 2D array - 4 by 3 size.**

In [ ]:
array_2d = np.zeros((4, 3))
array_2d

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

**6.Create 2D array with size 3 by 3. Elements values are random number(by default values between 0 to 1)**

In [ ]:
array_2d = np.random.rand(3, 3)
array_2d

array([[0.83306994, 0.81712038, 0.97861857],
       [0.15199568, 0.12976569, 0.79787595],
       [0.781668  , 0.12281626, 0.37586648]])

**7.Generate random value from range 5 to 15 with 2D array size 3 by 3.**

In [ ]:
random_array_3x3 = np.random.randint(5, 16,(3, 3))
random_array_3x3

array([[ 5, 15, 14],
       [15,  8,  5],
       [ 8,  9,  9]])

**8.Create 3D array with size 2 * 3 * 2.**

In [ ]:
array_3d = np.random.rand(2, 3, 2)
array_3d

array([[[0.00259408, 0.29732641],
        [0.0633782 , 0.96919177],
        [0.5737178 , 0.55552945]],

       [[0.18820916, 0.15846322],
        [0.14201963, 0.62644474],
        [0.1662073 , 0.86550617]]])

**9.Initialize 5 by 5 array with all values are zeros.**

In [ ]:
zero_array = np.zeros((5, 5))
zero_array

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

**10.Initialize 5 by 5 array with all values are ones.**

In [ ]:
ones_array = np.ones((5, 5))
ones_array


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

**11.Initialize 5 by 5 array with all values are particular values(consider 4).**

In [ ]:
array_of_four = np.full((5, 5), 4)
array_of_four

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

**12.Create indentity matrix with all diagonal values are 1 and rest all values are zeros.**

In [ ]:
identity_matrix = np.eye(5)
identity_matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

**13.Find out shape of array.**

In [ ]:
# Assuming we have an array named 'my_array1'
my_array1 = np.array([[1, 2, 3], [4, 5, 6]])
# Firstly we have Print the aary
my_array1
# Get the shape of the array
my_array1.shape


(2, 3)

In [ ]:
# Get the shape of the identity matrix
identity_matrix.shape

(5, 5)

**14.Find dimension of array.**

In [ ]:
# Get the dimension of the array
my_array1.ndim
identity_matrix.ndim

2

**15.Find no. of elements of from above any array.**

In [ ]:
my_array1.size

6

**16.Find type of array.**

In [ ]:
print(my_array1.dtype)
print(identity_matrix.dtype)
print(array_of_four.dtype)
print(ones_array.dtype)
print(array_2d.dtype)

int64
float64
int64
float64
float64


**17.Find maximum value from array.**

In [ ]:
print(my_array1.max())
print(identity_matrix.max())
print(array_3d.max())

6
1.0
0.9691917694412304


**18.Find minimum value from array.**

In [ ]:
print(my_array1.min())
print(identity_matrix.min())
print(array_2d.min())
print(array_3d.min())

1
0.0
0.12281625783020689
0.0025940756592913727


**19.Find average (mean) values from array.**

In [ ]:
print(my_array1.mean())
print(identity_matrix.mean())
print(array_2d.mean())
print(array_3d.mean())
print(array_of_four.mean())

3.5
0.2
0.5543107726948848
0.38404899468292614
4.0


**20.Find location of maximum value from array.**

In [ ]:
print(my_array1.argmax())
print(identity_matrix.argmax())
print(array_2d.argmax())
print(array_3d.argmax())

5
0
2
3


**21.Find location of maximum value from array.
Create two 2D array of size 3 by 3 and perform four basic mathematical operations.**

In [ ]:
x = np.random.randint(10,20,(3,3))
y = np.random.randint(10,50,(3,3))
print(x)
print(y)

# basic math operation
print("-------------")
print(x+y)
print(x-y)
print(x*y)
print(x/y)

[[13 14 18]
 [16 14 17]
 [18 16 12]]
[[46 31 45]
 [43 35 26]
 [22 12 11]]
-------------
[[59 45 63]
 [59 49 43]
 [40 28 23]]
[[-33 -17 -27]
 [-27 -21  -9]
 [ -4   4   1]]
[[598 434 810]
 [688 490 442]
 [396 192 132]]
[[0.2826087  0.4516129  0.4       ]
 [0.37209302 0.4        0.65384615]
 [0.81818182 1.33333333 1.09090909]]


**22.Print index 2 and -2 value for 1D array. (indexing).**

In [ ]:
print(arr[2])
print(arr[-2])

3
4


**23.Perform indexing operations with 2D array.**

In [ ]:
print(array_2d[1,2])
print(array_2d[0,:])
print(array_2d[:,2])
print(array_2d[0:2,1:3])

0.7978759545795516
[0.83306994 0.81712038 0.97861857]
[0.97861857 0.79787595 0.37586648]
[[0.81712038 0.97861857]
 [0.12976569 0.79787595]]


**24. Print value of index 2 to 5 (slicing)**

In [ ]:
print(arr[2:5])

[3 4 5]


**25. Print from index 0 to 5 values**

In [ ]:
print(arr[0:5])

[1 2 3 4 5]


**26. Print from index 5 to all**

In [ ]:
print(arr[5:])

[]


**27. Reassign value for particular index.**

In [ ]:
arr[2] = 10
arr

array([ 1,  2, 10,  4,  5])

**28.  Reassign value 100 to all elements.**

In [ ]:
arr[:] = 100
arr

array([100, 100, 100, 100, 100])

**29. Extract elements from index 1 to 7 with a step of 2**

In [ ]:
array = np.arange(10)  # Example array
extracted_elements = array[1:7:2]
print("Extracted Elements (Index 1 to 7, Step 2):", extracted_elements)

Extracted Elements (Index 1 to 7, Step 2): [1 3 5]


**30. Print Reverse the array.**

In [ ]:
print(arr[::-1])

[100 100 100 100 100]
